#!/usr/bin/env bash

## Set GTK Themes, Icons, Cursor and Fonts

THEME='Manhattan'
ICONS='Luv-Folders-Dark'
FONT='Noto Sans 9'
CURSOR='Qogirr-Dark'

SCHEMA='gsettings set org.gnome.desktop.interface'

apply_themes () {
	${SCHEMA} gtk-theme "$THEME"
	${SCHEMA} icon-theme "$ICONS"
	${SCHEMA} cursor-theme "$CURSOR"
	${SCHEMA} font-name "$FONT"
}

apply_themes
