#!/usr/bin/env bash

## Autostart Programs

# Kill already running processes
_ps=(waybar mako)
for _prs in "${_ps[@]}"; do
	if pidof "${_prs}" &> /dev/null; then
		killall "${_prs}"
	fi
done

# Polkit agent
pidof xfce-polkit &> /dev/null || /usr/lib/xfce-polkit/xfce-polkit &

# Apply themes
~/.config/hypr/scripts/gtkthemes &

# Launch notification daemon (mako)
~/.config/hypr/scripts/notifications &

# Launch statusbar (waybar)
~/.config/hypr/scripts/statusbar &

# Launch XDG
~/.config/hypr/scripts/xdg &

# Start network manager applet
nm-applet --indicator &
