#!/usr/bin/env bash

## Autostart Programs

# Kill already running processes to prevent duplicates
processes=(waybar mako)
for process in "${processes[@]}"; do
    if pidof "${process}" &>/dev/null; then
        killall "${process}"
    fi
done

# Apply themes
if [[ -x ~/.config/hypr/scripts/gtkthemes ]]; then
    ~/.config/hypr/scripts/gtkthemes &
fi

# Launch notification daemon (mako)
if [[ -x ~/.config/hypr/scripts/notifications ]]; then
    ~/.config/hypr/scripts/notifications &
fi

# Launch status bar (waybar)
if [[ -x ~/.config/hypr/scripts/statusbar ]]; then
    ~/.config/hypr/scripts/statusbar &
fi

# Reset XDG environment
if [[ -x ~/.config/hypr/scripts/xdg ]]; then
    ~/.config/hypr/scripts/xdg &
fi

# Reset Polkit agent
if [[ -x ~/.config/hypr/scripts/polkit ]]; then
    ~/.config/hypr/scripts/polkit &
fi

# Start Network Manager applet
if command -v nm-applet &>/dev/null; then
    nm-applet --indicator &
fi

# Start Hypridle
if command -v hypridle &>/dev/null; then
    hypridle &
fi

# Start Swww daemon
if command -v swww-daemon &>/dev/null; then
    swww-daemon &
fi
