#!/usr/bin/env bash

CONFIG="/home/gdam/.config/waybar/tokyonight/config"
STYLE="/home/gdam/.config/waybar/tokyonight/style.css"

if [[ ! `pidof waybar` ]]; then
	waybar --bar main-bar --log-level error --config ${CONFIG} --style ${STYLE}
fi
