#!/bin/bash

CONFIG="/home/gdam/.config/waybar/catppuccin/mocha/config"
STYLE="/home/gdam/.config/waybar/catppuccin/mocha/style.css"

# Verifica se o Waybar está rodando
if pgrep -x "waybar" > /dev/null
then
    # Se estiver rodando, envia o sinal SIGTERM para encerrar o Waybar
    killall -q waybar
else
    # Se não estiver rodando, inicia o Waybar
    waybar --bar main-bar --log-level error --config ${CONFIG} --style ${STYLE}
fi
