#!/usr/bin/env bash

WALLPAPER_DIR="$HOME/dotfiles/.config/hypr/wallpapers"
DEST_CURRENT="$WALLPAPER_DIR/current_wallpaper.png"

if [[ -z "$@" ]]; then
  find "$WALLPAPER_DIR" -type f \
    -not -name "README.md" \
    -not -name "active" \
    -not -name "current_wallpaper.png" |
    sed "s|$WALLPAPER_DIR/||"
else
  SELECTED="$WALLPAPER_DIR/$@"
  if [[ -f "$SELECTED" ]]; then
    swww img -t wipe --resize crop "$SELECTED"

    notify-send "Wallpaper Atualizado" "Wallpaper alterado para <i>$@</i>" -i "$SELECTED" -u normal

    cp "$SELECTED" "$WALLPAPER_DIR/active"
    rm -f "$DEST_CURRENT"
    convert "$SELECTED" "$DEST_CURRENT"
    wallust run "$SELECTED" >/dev/null 2>&1 &
    disown

    pkill -x rofi
  fi
fi
