#!/usr/bin/env bash

WALLPAPER_DIR="$HOME/dotfiles/.config/hypr/wallpapers"

if [[ -z "$@" ]]; then
    find "$WALLPAPER_DIR" -type f -not -name "README.md" -not -name "active" \
        | sed "s|$WALLPAPER_DIR/||"
else
    SELECTED="$WALLPAPER_DIR/$@"
    if [[ -f "$SELECTED" ]]; then
        swww img -t wipe --resize crop "$SELECTED"
        notify-send "Wallpaper Updated" "Desktop wallpaper changed to <i>$@</i>" -i "$SELECTED" -u normal
        cp "$SELECTED" "$WALLPAPER_DIR/active"
    fi
fi

