#!/usr/bin/env bash

for portal in hyprland gnome kde lxqt wlr ""; do
    pkill -x "xdg-desktop-portal-$portal" 2>/dev/null
done

sleep 1

if [[ -d /run/current-system/sw/libexec ]]; then
    libDir="/run/current-system/sw/libexec"  
elif [[ -d /usr/lib/xdg-desktop-portal ]]; then
    libDir="/usr/lib/xdg-desktop-portal"
else
    libDir="/usr/lib"
fi

# Iniciar o portal específico do Hyprland
if command -v "$libDir/xdg-desktop-portal-hyprland" &>/dev/null; then
    "$libDir/xdg-desktop-portal-hyprland" &
else
    echo "Erro: xdg-desktop-portal-hyprland não encontrado em $libDir"
fi

# Pausa para garantir que o portal específico seja carregado antes do genérico
sleep 2

# Iniciar o xdg-desktop-portal genérico
if command -v "$libDir/xdg-desktop-portal" &>/dev/null; then
    "$libDir/xdg-desktop-portal" &
else
    echo "Erro: xdg-desktop-portal não encontrado em $libDir"
fi

