backend = "kmeans"
color_space = "labmixed"
palette = "dark16"
threshold = 11

[templates]

hypr.template = 'colors-hypr.conf'
hypr.target = '~/.config/hypr/wallust.conf'

kitty.template = 'colors-kitty.conf'
kitty.target = '~/.config/kitty/colors.conf'

rofi.template = 'colors-rofi.rasi'
rofi.target = '~/.config/rofi/shared/colors.rasi'

waybar.template = 'colors-waybar.css'
waybar.target = '~/.config/waybar/colors-waybar.css'
