##############################
### WINDOWS AND WORKSPACES ###
##############################
# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more
# See https://wiki.hyprland.org/Configuring/Workspace-Rules/ for workspace rules

# Bind workspace to monitor
workspace=1, monitor:eDP-1
workspace=2, monitor:HDMI-A-1
workspace=3, monitor:HDMI-A-1
workspace=4, monitor:HDMI-A-1
workspace=5, monitor:HDMI-A-1


windowrulev2 = suppressevent maximize, class:.*

# nm-connection-editor floating
windowrulev2 = float, class:(.*nm-connection-editor.*)
windowrulev2 = size 35% 35%, class:(.*nm-connection-editor.*)
windowrulev2 = center,class:(.*nm-connection-editor.*)

# Blueman-manager floating
windowrulev2 = float, class:(.*blueman-manager.*)
windowrulev2 = size 35% 35%, class:(.*blueman-manager.*)
windowrulev2 = center,class:(.*blueman-manager.*)

# thunar floating
windowrulev2 = float, class:(.*thunar.*)
windowrulev2 = size 70% 70%, class:(.*thunar.*)
windowrulev2 = center,class:(.*thunar.*)

# Pavucontrol floating
windowrulev2 = float,class:(.*org.pulseaudio.pavucontrol.*)
windowrulev2 = size 700 600,class:(.*org.pulseaudio.pavucontrol.*)
windowrulev2 = center,class:(.*org.pulseaudio.pavucontrol.*)

# Waypaper floating
windowrulev2 = float,class:(.*waypaper.*)
windowrulev2 = size 800 700,class:(.*waypaper.*)
windowrulev2 = center,class:(.*waypaper.*)

# Thunderbird config
windowrulev2 = workspace 5 silent, class:(thunderbird)

# VScode config
windowrulev2 = workspace 3, class:(Code)

#Spotify config
windowrulev2 = workspace 1 silent, class:(Spotify)

# Vesktop config
windowrulev2 = workspace 1 silent, class:(vesktop)

# Zen Browser config
windowrulev2 = workspace 3, class:(zen-alpha)
# General floating
windowrulev2 = float,class:(dotfiles-floating)
windowrulev2 = size 1000 800,class:(dotfiles-floating)
windowrulev2 = center,class:(dotfiles-floating)

# Zen floating
windowrulev2 = float,class:(.*zen-alpha.*),title:(.*Picture-in-Picture.*)
windowrulev2 = size 636 358, class:(.*zen-alpha.*),title:(.*Picture-in-Picture.*)
windowrulev2 = move 1250 700, class:(.*zen-alpha.*),title:(.*Picture-in-Picture.*)
windowrulev2 = pin, class:(.*zen-alpha.*),title:(.*Picture-in-Picture.*)
